services:
  - type: web
    name: internconnect-ai-server
    env: node
    buildCommand: npm run postinstall && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
