// Comprehensive Mock Data for InternConnect AI SaaS Platform

export const MOCK_USERS = [
  {
    id: 'usr_student_1',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@example.com',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    college: 'IIT Delhi',
    degree: 'B.Tech in Computer Science',
    graduationYear: 2025,
    phone: '+91 98765 43210',
    bio: 'Passionate full-stack developer with a strong foundation in React, Node.js, and AI systems.',
    skills: ['React.js', 'Node.js', 'Python', 'TypeScript', 'Tailwind CSS', 'MongoDB', 'Docker'],
    github: 'https://github.com/aarav-sharma',
    linkedin: 'https://linkedin.com/in/aarav-sharma',
    portfolio: 'https://aaravsharma.dev',
    profileCompletion: 88,
    resume: {
      fileName: 'Aarav_Sharma_Resume_2025.pdf',
      fileSize: '1.2 MB',
      uploadedAt: '2026-08-20T10:30:00Z',
      url: '#',
    },
    experience: [
      {
        id: 'exp_1',
        title: 'Frontend Intern',
        company: 'TechCraft Labs',
        duration: 'May 2025 - Aug 2025',
        description: 'Built responsive dashboard components using React and Tailwind CSS.',
      },
    ],
    certifications: [
      { id: 'cert_1', name: 'AWS Certified Cloud Practitioner', issuer: 'Amazon Web Services', year: '2025' },
      { id: 'cert_2', name: 'Meta Front-End Developer Specialization', issuer: 'Coursera', year: '2024' },
    ],
  },
  {
    id: 'usr_company_1',
    name: 'Sarah Jenkins',
    email: 'recruiter@microsoft.com',
    role: 'company',
    companyId: 'comp_microsoft',
    companyName: 'Microsoft',
    designation: 'Senior Talent Acquisition Partner',
  },
  {
    id: 'usr_admin_1',
    name: 'System Administrator',
    email: 'admin@internconnect.ai',
    role: 'admin',
  },
];

export const MOCK_COMPANIES = [
  {
    id: 'comp_google',
    name: 'Google',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg',
    industry: 'Technology & Cloud',
    size: '100,000+ employees',
    location: 'Mountain View, CA / Bengaluru, IN',
    website: 'https://google.com/careers',
    description: 'Organizing the world’s information and making it universally accessible and useful.',
    verified: true,
    rating: 4.9,
    openingsCount: 12,
  },
  {
    id: 'comp_microsoft',
    name: 'Microsoft',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg',
    industry: 'Enterprise Software & Cloud',
    size: '150,000+ employees',
    location: 'Redmond, WA / Hyderabad, IN',
    website: 'https://careers.microsoft.com',
    description: 'Empowering every person and organization on the planet to achieve more.',
    verified: true,
    rating: 4.8,
    openingsCount: 8,
  },
  {
    id: 'comp_amazon',
    name: 'Amazon',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg',
    industry: 'E-Commerce & AWS',
    size: '1,000,000+ employees',
    location: 'Seattle, WA / Bengaluru, IN',
    website: 'https://amazon.jobs',
    description: 'Earth’s most customer-centric company, technology pioneer, and cloud platform leader.',
    verified: true,
    rating: 4.7,
    openingsCount: 15,
  },
  {
    id: 'comp_infosys',
    name: 'Infosys',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/9/95/Infosys_logo.svg',
    industry: 'IT Services & Consulting',
    size: '300,000+ employees',
    location: 'Bengaluru, India',
    website: 'https://infosys.com/careers',
    description: 'A global leader in next-generation digital services and consulting.',
    verified: true,
    rating: 4.5,
    openingsCount: 20,
  },
  {
    id: 'comp_tcs',
    name: 'TCS (Tata Consultancy Services)',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Tata_Consultancy_Services_Logo.svg',
    industry: 'IT & Business Solutions',
    size: '500,000+ employees',
    location: 'Mumbai, India',
    website: 'https://tcs.com/careers',
    description: 'Transforming businesses through innovation, IT services, and digital solutions.',
    verified: true,
    rating: 4.4,
    openingsCount: 25,
  },
  {
    id: 'comp_wipro',
    name: 'Wipro',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Wipro_Primary_Logo_Color_RGB.svg',
    industry: 'IT Services',
    size: '240,000+ employees',
    location: 'Bengaluru, India',
    website: 'https://wipro.com/careers',
    description: 'Leading global information technology, consulting, and business process services company.',
    verified: false, // For pending admin verification testing
    rating: 4.3,
    openingsCount: 10,
  },
];

export const MOCK_INTERNSHIPS = [
  {
    id: 'job_1',
    companyId: 'comp_google',
    companyName: 'Google',
    companyLogo: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg',
    title: 'Software Engineering Intern - Frontend (Summer 2026)',
    location: 'Bengaluru, Karnataka',
    workMode: 'Hybrid', // Remote, Hybrid, Onsite
    stipend: '₹85,000 / month',
    stipendValue: 85000,
    paid: true,
    duration: '3 Months',
    deadline: '2026-10-15',
    openings: 5,
    skills: ['React.js', 'TypeScript', 'JavaScript', 'HTML5/CSS3', 'Data Structures'],
    description: 'Join Google engineering teams to build modern web applications used by millions. You will collaborate with senior engineers to design, implement, and test frontend interfaces.',
    requirements: [
      'Pursuing B.Tech/M.Tech in Computer Science or related STEM field.',
      'Proficiency in React.js and modern JavaScript (ES6+).',
      'Solid understanding of data structures and object-oriented programming.',
    ],
    responsibilities: [
      'Develop scalable Web applications using React and TypeScript.',
      'Participate in code reviews, tech talks, and agile sprints.',
      'Optimize web pages for performance and accessibility.',
    ],
    postedAt: '2026-09-01T08:00:00Z',
    status: 'active', // active, closed, draft
    matchScore: 96,
    applicantsCount: 42,
    flagged: false,
  },
  {
    id: 'job_2',
    companyId: 'comp_microsoft',
    companyName: 'Microsoft',
    companyLogo: 'https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg',
    title: 'AI & Machine Learning Research Intern',
    location: 'Hyderabad, Telangana',
    workMode: 'Remote',
    stipend: '₹95,000 / month',
    stipendValue: 95000,
    paid: true,
    duration: '6 Months',
    deadline: '2026-11-01',
    openings: 3,
    skills: ['Python', 'PyTorch', 'TensorFlow', 'LLMs', 'Data Science'],
    description: 'Work with Microsoft AI Research group to prototype generative AI algorithms and NLP models.',
    requirements: [
      'Experience building machine learning models in Python using PyTorch or TensorFlow.',
      'Knowledge of neural networks, transformers, and vector databases.',
    ],
    responsibilities: [
      'Train fine-tuned LLM checkpoints.',
      'Document research benchmarks and contribute to technical papers.',
    ],
    postedAt: '2026-09-04T10:00:00Z',
    status: 'active',
    matchScore: 92,
    applicantsCount: 68,
    flagged: false,
  },
  {
    id: 'job_3',
    companyId: 'comp_amazon',
    companyName: 'Amazon',
    companyLogo: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg',
    title: 'Cloud Solutions & AWS DevOps Intern',
    location: 'Bengaluru / Remote',
    workMode: 'Remote',
    stipend: '₹75,000 / month',
    stipendValue: 75000,
    paid: true,
    duration: '3 Months',
    deadline: '2026-10-20',
    openings: 8,
    skills: ['AWS', 'Docker', 'Kubernetes', 'Linux', 'Python'],
    description: 'Assist AWS Cloud Architecture teams in building automated CI/CD pipelines and infrastructure as code.',
    requirements: [
      'Familiarity with AWS cloud services (EC2, S3, Lambda).',
      'Knowledge of containerization technologies like Docker.',
    ],
    responsibilities: [
      'Automate cloud deployments with Terraform and AWS CloudFormation.',
      'Monitor application metrics and log pipelines.',
    ],
    postedAt: '2026-09-02T12:00:00Z',
    status: 'active',
    matchScore: 88,
    applicantsCount: 35,
    flagged: false,
  },
  {
    id: 'job_4',
    companyId: 'comp_infosys',
    companyName: 'Infosys',
    companyLogo: 'https://upload.wikimedia.org/wikipedia/commons/9/95/Infosys_logo.svg',
    title: 'Cyber Security Analyst Intern',
    location: 'Pune, Maharashtra',
    workMode: 'Onsite',
    stipend: '₹35,000 / month',
    stipendValue: 35000,
    paid: true,
    duration: '4 Months',
    deadline: '2026-09-30',
    openings: 10,
    skills: ['Cyber Security', 'Network Security', 'Ethical Hacking', 'Linux', 'SIEM'],
    description: 'Perform vulnerability assessments, threat analysis, and network security monitoring.',
    requirements: [
      'Fundamental understanding of TCP/IP networking, firewalls, and cryptography.',
    ],
    responsibilities: [
      'Scan networks for security vulnerabilities.',
      'Assist security team in incident response simulations.',
    ],
    postedAt: '2026-08-28T09:00:00Z',
    status: 'active',
    matchScore: 78,
    applicantsCount: 51,
    flagged: false,
  },
  {
    id: 'job_5',
    companyId: 'comp_tcs',
    companyName: 'TCS',
    companyLogo: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Tata_Consultancy_Services_Logo.svg',
    title: 'Full Stack Web Developer Intern',
    location: 'Mumbai, Maharashtra',
    workMode: 'Hybrid',
    stipend: '₹40,000 / month',
    stipendValue: 40000,
    paid: true,
    duration: '6 Months',
    deadline: '2026-10-10',
    openings: 15,
    skills: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'REST APIs'],
    description: 'Develop end-to-end MERN stack web applications for global enterprise clients.',
    requirements: ['Experience with React, Node.js, Express, and MongoDB.'],
    responsibilities: ['Create REST APIs and frontend components.'],
    postedAt: '2026-09-03T11:00:00Z',
    status: 'active',
    matchScore: 95,
    applicantsCount: 89,
    flagged: false,
  },
  {
    id: 'job_6',
    companyId: 'comp_wipro',
    companyName: 'Wipro',
    companyLogo: 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Wipro_Primary_Logo_Color_RGB.svg',
    title: 'Mobile App Developer Intern (Flutter / React Native)',
    location: 'Chennai, Tamil Nadu',
    workMode: 'Onsite',
    stipend: '₹30,000 / month',
    stipendValue: 30000,
    paid: true,
    duration: '3 Months',
    deadline: '2026-10-05',
    openings: 4,
    skills: ['Mobile Development', 'Flutter', 'React Native', 'Dart', 'UI/UX'],
    description: 'Build cross-platform mobile apps for iOS and Android platforms.',
    requirements: ['Familiarity with Flutter or React Native mobile frameworks.'],
    responsibilities: ['Implement responsive UI designs and integrate third-party APIs.'],
    postedAt: '2026-09-05T14:00:00Z',
    status: 'active',
    matchScore: 82,
    applicantsCount: 29,
    flagged: false,
  },
];

export const MOCK_APPLICATIONS = [
  {
    id: 'app_1',
    jobId: 'job_1',
    jobTitle: 'Software Engineering Intern - Frontend (Summer 2026)',
    companyName: 'Google',
    companyLogo: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg',
    studentId: 'usr_student_1',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@example.com',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    studentCollege: 'IIT Delhi',
    studentDegree: 'B.Tech CS',
    appliedAt: '2026-09-02T14:30:00Z',
    status: 'Interview Scheduled', // Applied, Under Review, Shortlisted, Interview Scheduled, Selected, Rejected
    matchScore: 96,
    coverLetter: 'I am highly passionate about Google web products and have hands-on experience building performant React applications.',
    resumeName: 'Aarav_Sharma_Resume_2025.pdf',
    statusHistory: [
      { status: 'Applied', timestamp: '2026-09-02T14:30:00Z', note: 'Application submitted successfully.' },
      { status: 'Under Review', timestamp: '2026-09-04T09:15:00Z', note: 'Resume screened by talent acquisition team.' },
      { status: 'Shortlisted', timestamp: '2026-09-06T11:00:00Z', note: 'Candidate shortlisted for technical interview.' },
      { status: 'Interview Scheduled', timestamp: '2026-09-08T16:00:00Z', note: 'Round 1 Technical Interview scheduled for Sept 15, 2026.' },
    ],
    interviewDetails: {
      date: '2026-09-15',
      time: '14:00 - 15:00 IST',
      meetingLink: 'https://meet.google.com/abc-defg-hij',
      interviewer: 'Rahul Gupta (Senior Software Engineer @ Google)',
    },
  },
  {
    id: 'app_2',
    jobId: 'job_2',
    jobTitle: 'AI & Machine Learning Research Intern',
    companyName: 'Microsoft',
    companyLogo: 'https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg',
    studentId: 'usr_student_1',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@example.com',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    studentCollege: 'IIT Delhi',
    studentDegree: 'B.Tech CS',
    appliedAt: '2026-09-05T10:00:00Z',
    status: 'Shortlisted',
    matchScore: 92,
    coverLetter: 'Excited about PyTorch research and Generative AI at Microsoft.',
    resumeName: 'Aarav_Sharma_Resume_2025.pdf',
    statusHistory: [
      { status: 'Applied', timestamp: '2026-09-05T10:00:00Z', note: 'Application submitted.' },
      { status: 'Under Review', timestamp: '2026-09-07T08:30:00Z', note: 'Under recruiter review.' },
      { status: 'Shortlisted', timestamp: '2026-09-09T12:00:00Z', note: 'Candidate shortlisted!' },
    ],
  },
  {
    id: 'app_3',
    jobId: 'job_5',
    jobTitle: 'Full Stack Web Developer Intern',
    companyName: 'TCS',
    companyLogo: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Tata_Consultancy_Services_Logo.svg',
    studentId: 'usr_student_1',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@example.com',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    studentCollege: 'IIT Delhi',
    studentDegree: 'B.Tech CS',
    appliedAt: '2026-09-04T16:20:00Z',
    status: 'Under Review',
    matchScore: 95,
    coverLetter: 'Full stack development with Node.js and MongoDB.',
    resumeName: 'Aarav_Sharma_Resume_2025.pdf',
    statusHistory: [
      { status: 'Applied', timestamp: '2026-09-04T16:20:00Z', note: 'Application submitted.' },
      { status: 'Under Review', timestamp: '2026-09-06T10:00:00Z', note: 'Review in progress.' },
    ],
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 'notif_1',
    title: 'Interview Scheduled with Google!',
    message: 'Your Round 1 Technical Interview for Frontend Intern is scheduled for Sept 15 at 2:00 PM IST.',
    timestamp: '2 hours ago',
    read: false,
    type: 'interview', // interview, application, job, system
    link: '/application-tracker',
  },
  {
    id: 'notif_2',
    title: 'Shortlisted by Microsoft',
    message: 'Congratulations! Microsoft has shortlisted your resume for AI & ML Research Intern.',
    timestamp: '1 day ago',
    read: false,
    type: 'application',
    link: '/application-tracker',
  },
  {
    id: 'notif_3',
    title: 'New Internship Matching Your Profile',
    message: 'Amazon posted a new opening: Cloud Solutions & AWS DevOps Intern.',
    timestamp: '2 days ago',
    read: true,
    type: 'job',
    link: '/explore',
  },
];
